import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";


const Home: NextPage = () => {

  return (
    <>
      <Head>
        <title>Roland VD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="sticky top-0 flex justify-between items-center bg-ebony-clay-900 py-4 px-8">
        <div>
          <h1 className="text-white text-2xl font-semibold">Roland Van Duine</h1>
        </div>
        <nav className="flex gap-6 text-lg font-semibold">
          <a href="/about" className="text-white hover:text-gray-300">About</a>
          <a href="/project" className="text-white hover:text-gray-300">Project</a>
          <a href="/contact" className="text-white hover:text-gray-300">Contact</a>
          <a href="/blog" className="text-white hover:text-gray-300">Newsletter</a>
        </nav>
      </header>
      <main className="flex min-h-screen flex-col items-center justify-center bg-ebony-clay-950">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Roland <span className="text-mandy-500">Van</span> Duine
          </h1>
          <p className="text-2xl text-white">WIP</p>
        </div>
      </main>
    </>
  );
};

export default Home;
